# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  #- osx

julia:
  - 1.1

codecov: true
coveralls: true


matrix:
  allow_failures:
    - julia: nightly

addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-dev
notifications:
  email:
    false

## uncomment the following lines to override the default test script
script:
 - julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test()'
