# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  #- osx

julia:
  - 1.1

codecov: true
coveralls: true


matrix:
  allow_failures:
    - julia: nightly

addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-dev
notifications:
  email:
    false

## uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
  - $TESTCMD -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
